// some comment
const categories = [
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
  { id: '1ab', name: 'electronics' },
  { id: '3ad', name: 'samsung', parentId: '2ac' },
  { id: '4ad', name: 'oppo', parentId: '2ac' },
  { id: '5ad', name: 'vivo', parentId: '2ac' },
  { id: '2ac', name: 'mobile', parentId: '1ab' },
  { id: '1zb', name: 'mens' },
  { id: '2zb', name: 'womens' },
  { id: '2zc', name: 'dress', parentId: '1zb' },
  { id: '3zc', name: 'dress', parentId: '2zb' },
  { id: '3zd', name: 't-shirt', parentId: '2zc' },
  { id: '3zd', name: 'plazu', parentId: '3zc' },
];

console.time('traversing');
const parentCategory = categories.filter((cat) => !cat.parentId);
const finalCategory = parentCategory.map((pCat) => {
  const childOfParent = categories.filter((ctg) => ctg.parentId === pCat.id);
  const modifiedChildOfParentWithChildOfChild = childOfParent.map((cat) => {
    const childOfChild = categories.filter((cCat) => cCat.parentId === cat.id);
    return { ...cat, children: childOfChild };
  });
  return { ...pCat, children: modifiedChildOfParentWithChildOfChild };
});
console.timeEnd('traversing');

console.time('recursive');
function createCategories(categories, parentId = null) {
  const categoryList = [];
  let category;
  if (parentId == null) {
    category = categories.filter((cat) => cat.parentId == undefined);
  } else {
    category = categories.filter((cat) => cat.parentId == parentId);
  }
  for (let cate of category) {
    categoryList.push({
      id: cate.id,
      name: cate.name,
      parentId: cate.parentId,
      children: createCategories(categories, cate.id),
    });
  }
  return categoryList;
}
createCategories(categories);
console.timeEnd('recursive');
